### ISSUE TITLE
Add converters for common of types

### ISSUE THREAD

**Issue by s-ol** [michaelbaisch/ofxYAML#1]
for example for glm vectors:
```
namespace YAML {
  template<typename T>
  struct convert<glm::tvec2<T>> {
    static Node encode(const glm::tvec2<T>& rhs) {
      Node node;
      node.push_back(rhs.x);
      node.push_back(rhs.y);
      return node;
    }

    static bool decode(const Node& node, glm::tvec2<T>& rhs) {
      if (!node.IsSequence() || node.size() != 2) {
        return false;
      }

      rhs.x = node[0].as<T>();
      rhs.y = node[1].as<T>();
      return true;
    }
  };
  template<typename T>
  struct convert<glm::tvec3<T>> {
    static Node encode(const glm::tvec3<T>& rhs) {
      Node node;
      node.push_back(rhs.x);
      node.push_back(rhs.y);
      node.push_back(rhs.z);
      return node;
    }

    static bool decode(const Node& node, glm::tvec3<T>& rhs) {
      if (!node.IsSequence() || node.size() != 3) {
        return false;
      }

      rhs.x = node[0].as<T>();
      rhs.y = node[1].as<T>();
      rhs.z = node[2].as<T>();
      return true;
    }
  };
  template<typename T>
  struct convert<glm::tvec4<T>> {
    static Node encode(const glm::tvec4<T>& rhs) {
      Node node;
      node.push_back(rhs.x);
      node.push_back(rhs.y);
      node.push_back(rhs.z);
      node.push_back(rhs.w);
      return node;
    }

    static bool decode(const Node& node, glm::tvec4<T>& rhs) {
      if(!node.IsSequence() || node.size() != 4) {
        return false;
      }

      rhs.x = node[0].as<T>();
      rhs.y = node[1].as<T>();
      rhs.z = node[2].as<T>();
      rhs.w = node[3].as<T>();
      return true;
    }
  };
}
```

**Comment by michaelbaisch** [comment]
Yeah that's a good idea. But may I ask why you choose the `glm::tvec` types? I think I would implement the oF types like `ofVec3f`.

**Comment by s-ol** [comment]
@michaelbaisch totally, i just pasted this from my project where I use the glm vectors directly. Not that it would matter much though, as they [convert back and forth seamlessly](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/math/ofVec3f.h#L130)

**Comment by michaelbaisch** [comment]
I've added convertors for OF vector types, see here https://github.com/michaelbaisch/ofxYAML/commit/3b5a2ae70df59bebd2a02b7b099350dfbe3cf1d5 .
If you have any thoughts, let me know.

**Comment by s-ol** [comment]
hm, looks good but why does it need the extra templates?

**Comment by michaelbaisch** [comment]
That's very simple I wanted to prevent duplication of code.

**Comment by s-ol** [comment]
ah, i didn't look closely enough and didn't see the second reference. Maybe it would be a bit cleaner to move those helpers to a `namespace internal` or something like that instead of putting them into the YAML one. Other than that looks good to me :+1: 

Maybe you would want to add `ofRectangle` as well, thats the only other one that I can think of as useful to implement right now (`ofPoint` is a typedef of ofVec so its covered).

**Comment by s-ol** [comment]
@michaelbaisch i found two typos/bugs, commented on the commit itself.

**Comment by michaelbaisch** [comment]
How embarrassing… should be fixed now https://github.com/michaelbaisch/ofxYAML/commit/92a5723c7d311070dc4f254364bb2e523dc9c6d7

**Comment by s-ol** [comment]
@michaelbaisch no worries, this kind of thing is easy to miss with templates :)

Thanks for the quick response(s)!
