### ISSUE TITLE
Peel off a node to pass as an argument?

### ISSUE THREAD

**Issue by tedmoore** [michaelbaisch/ofxYAML#3]
I just left this over on the oF Discourse, but thought I'd ask here as well if you can help!

I’m using ofxYAML to load some information from a config file. I can’t figure out how to peel off one node of the YAML tree to pass as an argument to a function. For example, I want to do something like this:

```
ofxYAML config;
config.load("config.yaml");

int n_modules = 5;

for(int i = 0; i < n_modules; i++){
    ofxYAML child = config["module-" + ofToString(i)];
    modules[i]->loadState(child);
}
```

The error I get says `No viable conversion from 'YAML::Node' to 'ofxYAML'`

Any guidance is much appreciated!

Thanks,

Ted

**Comment by michaelbaisch** [comment]
Sounds like you should use the `YAML::Node` and not `ofxYAML` as type of your `child` variable and then go from there.

**Comment by tedmoore** [comment]
Thank you! Yes, this works.
